name: Ruby CI

on: [push]

jobs:
  setup:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler: '2.4.20'
          cache: true

      - name: Bundle Install
        run: bundle install --path vendor/bundle

      - name: Prepare Database
        run: |
          bin/rails db:create db:schema:load
        services:
          postgres:
            image: postgres
            ports:
              - "5432:5432"
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            env:
              POSTGRES_DB: rails_test
              POSTGRES_USER: rails
              POSTGRES_PASSWORD: password

  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Rubocop
        run: bundle exec rubocop --parallel

  bundle_audit:
    name: Bundle Audit
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bundle Audit
        run: bundle exec bundle-audit check --update

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Brakeman
        run: bundle exec brakeman

  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    needs: setup
    env:
      RAILS_ENV: test
    services:
      postgres:
        image: postgres
        ports:
          - "5432:5432"
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Rspec Tests
        run: bundle exec rspec
